/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.chkpnt.gradle.plugin.servicedienste

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.plugins.BasePlugin

/**
 * A simple 'hello world' plugin.
 */
class ServicedienstePlugin: Plugin<Project> {

    override fun apply(project: Project) {
        project.pluginManager
                .apply(BasePlugin::class.java)

        val extension = project.extensions
                .create(SERVICEDIENSTE_EXTENSION_NAME, ServicediensteExtension::class.java, project)

        project.tasks.register(SERVICEDIENSTE_CONVERSION_TASK_NAME, ServicediensteConversionTask::class.java)

        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'de.chkpnt.gradle.plugin.servicedienste.greeting'")
            }
        }
    }

    companion object {

        private val SERVICEDIENSTE_EXTENSION_NAME = "servicedienste"
        private val SERVICEDIENSTE_CONVERSION_TASK_NAME = "convertServicedienste"
    }
}
